# Server Configuration
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        name: ES_SESSIONID

# Spring Boot Application Name
spring:
  application:
    name: EasyStock

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/easystock
    username: postgres
    password: houssam
    driver-class-name: org.postgresql.Driver

  # Hibernate/JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Liquibase Database Migration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

# Application-specific properties
app:
  tva:
    rate: 0.20